### ISSUE TITLE
Wrong distance?

### ISSUE THREAD

**Issue by christophlingg** [jtreml/leaflet.measure#3]
in your demo, the distance is given in **nm**. Are these really nanometres? Seems like a bug.

**Comment by jtreml** [comment]
nm = Nautical Miles (which equal 1.852 km each). in any case, it's easy enough to change... internal calculations are done in meters and the final conversion and rounding is done [here](../blob/master/leaflet.measure/leaflet.measure.js#L221).

``` javascript
    _round: function(val) {
        return Math.round((val / 1852) * 10) / 10;
    },
```

`val` is in meters, dividing by 1852 gives nautical miles. you could divide by 1150.78 to get miles for example.

**Comment by christophlingg** [comment]
thanks for pointing this out!
